### PR TITLE
Export `@trinsic/trinsic/browser` properly

### PR DESCRIPTION
**Pull request by fundthmcalculus**

### CODE REVIEW

**Review by tmarkovski — COMMENTED** [review]
Shouldn't this load from lib or are we keeping everything in src now?

**Comment by fundthmcalculus** [comment]
I tried that. That was what required the lib browser import directive. Apparently you can't have a default import from a lib folder from what I can tell.

**Comment by fundthmcalculus** [comment]
This looks promising: https://github.com/nodejs/node/issues/14970#issuecomment-570036324

**Comment by fundthmcalculus** [comment]
Appears to work locally, testing with one final rc before sending https://github.com/trinsic-id/sdk/issues/881

**Comment by fundthmcalculus** [comment]
It works as expected.

**Review by tmarkovski — APPROVED** [review]
\o/

**Review by geel9 — APPROVED** [review]

**Pull request merged**
