### PR TITLE
docs: Remove github doc attribution

### PR DESCRIPTION
**Pull request by fundthmcalculus**
* Closes https://github.com/trinsic-id/server/issues/1762

### CODE REVIEW

**Review by tmarkovski — APPROVED** [review]

**Comment by janpieterz** [comment]
Looks like there's still attribution 
image

**Review by janpieterz — DISMISSED** [review]
Looks like attribution is still there

**Comment by janpieterz** [comment]
Looks like there's still attribution 
image

**Comment by fundthmcalculus** [comment]
> Looks like attribution is still there

I think that's a caching issue. Let me check further.

**Pull request merged**
