### PR TITLE
Reduce docs font size

### PR DESCRIPTION
**Pull request by tmarkovski**

### CODE REVIEW

**Review by fundthmcalculus — COMMENTED** [review]
I'm fine with the change, I'd defer to @michaeldboyd on this though.

**Review by janpieterz — APPROVED** [review]

**Comment by geel9** [comment]
Looking at the generated preview, it looks kind of strange -- comparing it to the live version, it seems like the entire page is being squished down, not just the font size

**Comment by geel9** [comment]
I guess that's actually because everything is using `em` for spacing.

Overall I guess I'm fine with it

**Comment by tmarkovski** [comment]
> I guess that's actually because everything is using `em` for spacing.
> 
> Overall I guess I'm fine with it

Yeah, some of the items will need fine tuning. I think some of the font sizes we added appear overtuned now. It's not perfect, but the original size was just too large.

**Comment by geel9** [comment]
I definitely agree that the font is simply way too big as-is. It's been bugging me for some time.

**Pull request merged**
