### PR TITLE
tests: Add node tests for CredentialService and Templates

### PR DESCRIPTION
**Pull request by janpieterz**

### CODE REVIEW

**Review by fundthmcalculus — APPROVED** [review]
I thought we already had this test in the VaccineShared.ts file?

**Comment by janpieterz** [comment]
@fundthmcalculus Mmmh, yea, maybe? it's tough to compare those tests, I just noticed we ran some on Browser but not node during a debug session so tackled this. We can refactor this a bit in the future.

**Comment by fundthmcalculus** [comment]
The shared component is there so we aren't duplicating code between node and browser. It looks like all the checks failed, so something is broken.

**Comment by janpieterz** [comment]
I'll check it out :)

**Pull request merged**
