### PR TITLE
Copied Protos from server - deprecate `ProviderService.Invite()` and `ProviderService.InvitationStatus()`

### PR DESCRIPTION
**Pull request by mewmba**
:crown: copied proto files from server repo

### CODE REVIEW

**Comment by janpieterz** [comment]
@fundthmcalculus what's the idea with those failed ones? Are they manually crafted (aka I need to edit)?

**Comment by fundthmcalculus** [comment]
> @fundthmcalculus what's the idea with those failed ones? Are they manually crafted (aka I need to edit)?

Unrecognized named-value: 'secrets'. Located at position 1 within expression: secrets.API_GITHUB_TOKEN issue with the `action.yml`. Hang on a moment.

**Comment by fundthmcalculus** [comment]
Here's the PR fix: https://github.com/trinsic-id/sdk/pull/1211

**Comment by fundthmcalculus** [comment]
Looks like .NET is using obsolete code which is a warning converted to error.

**Review by fundthmcalculus — APPROVED** [review]

**Pull request merged**
