### PR TITLE
refactor: Deprecate webhooks

### PR DESCRIPTION
**Pull request by mewmba**
:crown: copied proto files from server repo: 9aa58525 refactor: Remove unused and obsolete Grant from Provider proto (#1791)
***UPDATE THIS AND PR TITLE***

### CODE REVIEW

**Comment by janpieterz** [comment]
@fundthmcalculus  Weird, no dotnet updates, doesn't look like the webhooks methods are removed in the Typescript one at least, any ideas?

**Comment by fundthmcalculus** [comment]
I'll take a look when I get home. That's odd that it didn't seem to remove it because it should have.

**Comment by janpieterz** [comment]
Ouch, it's now blending changes into one branch. We should probably change this so that the mewmba changes don't override each other in the sdk, e.g. by copying branch names and doing server/xyz => sdk/xyz and sdk/xyz-generated or something?

**Comment by fundthmcalculus** [comment]
> Ouch, it's now blending changes into one branch. We should probably change this so that the mewmba changes don't override each other in the sdk, e.g. by copying branch names and doing server/xyz => sdk/xyz and sdk/xyz-generated or something?

No argument there. That's been a low priority item for me, but I can definitely do that.

**Review by fundthmcalculus — APPROVED** [review]

**Pull request merged**
