### PR TITLE
Fix broken tests

### PR DESCRIPTION
**Pull request by fundthmcalculus**
* Fix tests for removed endpoints.
* We need to do a better job of either addressing the tests when a PR is opened (and fails on CI), or notifying me that it needs to be fixed.

### CODE REVIEW

**Review by geel9 — APPROVED** [review]

**Comment by janpieterz** [comment]
@fundthmcalculus if they fail on CI how does it get merged?

**Comment by fundthmcalculus** [comment]
That was more in common about people not updating when they just close the mewmba PRs. In this case, I told Ciara to merge while I wrote the tests so that she wasn't blocked on OIDC work.

**Comment by janpieterz** [comment]
Ah I see - aren't we compiling these samples and tests? The CI should find this no?

**Comment by fundthmcalculus** [comment]
It does. The problem has been that most people see the CI failures and just close the PR rather than actually merging any updates.

**Pull request merged**
