### PR TITLE
build: Make release installers work

### PR DESCRIPTION
**Pull request by fundthmcalculus**
* Use proper version of `set-version`
* Call homebrew update directly
* Set up wix installer PR

### CODE REVIEW

**Review by tmarkovski — APPROVED** [review]

**Comment by tmarkovski** [comment]
@fundthmcalculus Bump. Progress on this?

**Comment by fundthmcalculus** [comment]
We haven't released the SDK in a while, and given that `winget` doesn't handle peer dependencies (MSVCRT in our case) yet, we can't really make this work. I'd rather finish this work, but it's a priority call.

**Comment by janpieterz** [comment]
This is for the CLI? I'd say deprioritize in that case.

**Comment by fundthmcalculus** [comment]
It is for the CLI, let's close it.

**Pull request closed without merging**
